name: enough_mail_app
description: Maily aims to become a fully feature email app once it has grown up.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+84

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  background_fetch: ^1.1.0
  badges: ^2.0.2
  cached_network_image: ^3.2.1
  community_material_icon: ^5.9.55
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  crypto: ^3.0.2
  device_info_plus: ^3.2.1
  enough_mail: ^2.0.0
  enough_mail_flutter: ^2.0.0
  enough_mail_html: ^2.0.0
  enough_html_editor: ^0.0.3
  enough_text_editor: 
    git:
      url: https://github.com/Enough-Software/enough_text_editor.git
  enough_icalendar: ^0.5.0
  enough_mail_icalendar: ^0.2.0
  enough_media: ^2.2.0
  enough_icalendar_export: ^0.2.0
  enough_serialization: ^1.4.0
  enough_ascii_art: ^1.0.0
  enough_giphy_flutter: ^0.3.0
  enough_platform_widgets: ^0.3.0
  event_bus: ^2.0.0
  file_picker: ^4.2.7
  flutter:
    sdk: flutter
  fluttercontactpicker: ^4.7.0
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^11.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  flutter_web_auth: ^0.4.0
  flutter_widget_from_html_core: ^0.8.3+1
  get_it: ^7.2.0 
  google_fonts: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  latlng: ^0.2.0
  local_auth: ^2.1.0
  location: ^4.4.0
  map: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  open_settings: ^2.0.2
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  share_plus: ^4.0.4
  shared_preferences: ^2.0.11
  shimmer_animation: ^2.1.0+1
  # snapping_sheet: ^3.1.0
  url_launcher: ^6.0.17
  webview_flutter: ^3.0.0

dependency_overrides:
  xml: ^6.1.0
  flutter_inappwebview:
    git: https://github.com/CodeEagle/flutter_inappwebview
  # out-comment the following to enable git-based development:
  enough_mail:
    git:
      url: https://github.com/Enough-Software/enough_mail.git
  enough_mail_flutter:
    git:
      url: https://github.com/Enough-Software/enough_mail_flutter.git
  enough_icalendar: 
    git:
      url: https://github.com/Enough-Software/enough_icalendar.git
  enough_mail_icalendar: 
    git:
      url: https://github.com/Enough-Software/enough_mail_icalendar.git
  enough_icalendar_export: 
    git:
      url: https://github.com/Enough-Software/enough_icalendar_export.git
  enough_html_editor: 
    git:
      url: https://github.com/Enough-Software/enough_html_editor.git
  enough_text_editor: 
    git:
      url: https://github.com/Enough-Software/enough_text_editor.git
  #enough_serialization:
    # git:
    #   url: https://github.com/Enough-Software/enough_serialization.git
  enough_ascii_art: 
    git:
      url: https://github.com/Enough-Software/enough_ascii_art.git
  enough_giphy_flutter:
    git:
      url: https://github.com/Enough-Software/enough_giphy_flutter.git
  enough_platform_widgets: 
    git:
      url: https://github.com/Enough-Software/enough_platform_widgets.git

  # out-comment the following to enable local development:
  # enough_mail:
  #   path: ../enough_mail
  # enough_mail_flutter:
  #   path: ../enough_mail_flutter
  # enough_mail_html:
  #   path: ../enough_mail_html
  # enough_icalendar:
  #   path: ../enough_icalendar
  # enough_mail_icalendar:
  #   path: ../enough_mail_icalendar
  # enough_icalendar_export:
  #   path: ../enough_icalendar_export  
  # enough_media:
  #   path: ../enough_media
  # enough_html_editor: 
  #   path: ../enough_html_editor
  # enough_text_editor:
  #   path: ../enough_text_editor
  # enough_ascii_art:
  #   path: ../enough_ascii_art
  # enough_giphy_flutter:
  #   path: ../enough_giphy_flutter
  # enough_platform_widgets:
  #   path: ../enough_platform_widgets

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # For localization / l10n:
  generate: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/providers/
    - assets/keys.txt
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
